# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 11:14
from __future__ import unicode_literals

from django.contrib.contenttypes.management import create_contenttypes
from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_aether_permissions(apps, schema_editor):
    app_config = apps.get_app_config('odk')
    app_config.models_module = 'aether.odk.api.migrations'
    create_contenttypes(app_config)
    create_permissions(app_config)


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0007_xform_modified_at'),
    ]

    operations = [
        migrations.RunPython(create_aether_permissions, migrations.RunPython.noop)
    ]
