# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0008_create_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['xform', 'name'], 'permissions': (('view_mediafile', 'Can view MediaFile'),), 'verbose_name': 'media file', 'verbose_name_plural': 'media files'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('view_project', 'Can view Project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='xform',
            options={'ordering': ['title', 'form_id', 'version'], 'permissions': (('view_xform', 'Can view XForm'),), 'verbose_name': 'xform', 'verbose_name_plural': 'xforms'},
        ),
    ]
