# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 11:24
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def create_user_view_permission(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(get_user_model())
    Permission.objects.create(
        codename='view_user',
        name='Can view user',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0009_auto_20181203_1115'),
    ]

    operations = [
        migrations.RunPython(create_user_view_permission, migrations.RunPython.noop)
    ]
