# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_project_artefacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedb',
            options={'ordering': ['-last_synced_date'], 'permissions': (('view_devicedb', 'Can view device'),), 'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='mobileuser',
            options={'ordering': ['email'], 'permissions': (('view_mobileuser', 'Can view mobile user'),), 'verbose_name': 'mobile user', 'verbose_name_plural': 'mobile users'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('view_project', 'Can view project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['name'], 'permissions': (('view_schema', 'Can view schema'),), 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
    ]
