# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 10:57
from __future__ import unicode_literals

from django.contrib.contenttypes.management import create_contenttypes
from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_aether_permissions(apps, schema_editor):
    app_config = apps.get_app_config('sync')
    app_config.models_module = 'aether.sync.api.migrations'
    create_contenttypes(app_config)
    create_permissions(app_config)


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_auto_20181203_1041'),
    ]

    operations = [
        migrations.RunPython(create_aether_permissions, migrations.RunPython.noop)
    ]
