# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0022_create_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['submission__id', 'name'], 'permissions': (('view_attachment', 'Can view Attachment'),), 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['project__id', '-modified'], 'permissions': (('view_entity', 'Can view Entity'),), 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['project__id', '-modified'], 'permissions': (('view_mapping', 'Can view Mapping'),), 'verbose_name': 'mapping', 'verbose_name_plural': 'mappings'},
        ),
        migrations.AlterModelOptions(
            name='mappingset',
            options={'ordering': ['project__id', '-modified'], 'permissions': (('view_mappingset', 'Can view MappingSet'),), 'verbose_name': 'mapping set', 'verbose_name_plural': 'mapping sets'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified'], 'permissions': (('view_project', 'View project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ['project__id', '-modified'], 'permissions': (('view_projectschema', 'Can view ProjectSchema'),), 'verbose_name': 'project schema', 'verbose_name_plural': 'project schemas'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-modified'], 'permissions': (('view_schema', 'Can view Schema'),), 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['project__id', '-modified'], 'permissions': (('view_submission', 'Can view Submission'),), 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
    ]
